Update assignment3.yml

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -82,7 +82,8 @@ jobs:
         run: echo "Container up and running" >> /tmp/log.txt
       - name: Log run failure
         if: failure()
-        run: echo "Container failed to run" >> /tmp/log.txt     
+        run: echo "Container failed to run" >> /tmp/log.txt
+        exit 1
 
 
       - name: Check container status
