fix tests

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -74,16 +74,25 @@ jobs:
             exit 1
           fi
 
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Set up Python
-      uses: actions/setup-python@v4
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pytest 
-        pip install requests
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest 
+          pip install requests
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+      - name: Run tests
+        run: |
+          if -v pytest /tests/assn3_tests.py > assn3_test_results.txt; then
+            echo "Tests succeeded" >> log.txt
+          else
+            echo "Tests failed" >> log.txt
+            exit 1
+          fi
 
       - name: Upload test results and log
         uses: actions/upload-artifact@v3
