fix log gile

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -18,6 +18,9 @@ jobs:
       - name: Record start time
         run: echo "Start Time:$(date -Iminutes)" > log.txt
 
+      - name: Add submitter names to log
+        run: echo "Omer Yanay, Yuval Lapid" >> log.txt  
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
         
@@ -28,6 +31,13 @@ jobs:
           file: ./bookapi/Dockerfile
           tags: books:latest
           outputs: type=docker,dest=/tmp/image.tar
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "image successfully built" >> log.txt
+          else
+            echo "image not able to be built" >> log.txt
+            exit 1
+          fi  
 
       - name: Upload Docker image and log
         uses: actions/upload-artifact@v3
@@ -38,7 +48,7 @@ jobs:
       - name: Upload log
         uses: actions/upload-artifact@v3
         with:
-          name: build-log
+          name: log.txt
           path: log.txt
 
   test:
@@ -55,7 +65,14 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Set up Docker Compose
-        run: docker compose -f docker-compose.yml up -d
+        run: |
+          docker compose -f docker-compose.yml up -d
+          if [ $? -eq 0 ]; then
+            echo "Container up and running" >> log.txt
+          else
+            echo "Container failed to run" >> log.txt
+            exit 1
+          fi
 
       - name: Check container status
         run: docker ps
@@ -71,7 +88,14 @@ jobs:
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       - name: Run tests
-        run: pytest -v ./tests/assn3_tests.py > assn3_test_results.txt
+        run: |
+          pytest -v ./tests/assn3_tests.py > assn3_test_results.txt
+          if [ $? -eq 0 ]; then
+            echo "tests succeeded" >> log.txt
+          else
+            echo "tests failed" >> log.txt
+            exit 1
+          fi
 
       - name: Upload test results and log
         if: always()
